fix(cicd):clear pipeline

diff --git a/.github/workflows/01-socle-infra.yml b/.github/workflows/01-socle-infra.yml
--- a/.github/workflows/01-socle-infra.yml
+++ b/.github/workflows/01-socle-infra.yml
@@ -110,7 +110,6 @@ jobs:
       TF_VAR_ip_ntp_1: ${{ vars.TF_IP_NTP_01 }}
       TF_VAR_ip_addns_01: ${{ vars.TF_IP_ADDNS_01 }}
       TF_VAR_ip_addns_02: ${{ vars.TF_IP_ADDNS_02 }}
-      # TF_VAR_ip_rsys_01: ${{ vars.TF_IP_RSYS_01 }}
       TF_VAR_gateway_vlan70: ${{ vars.TF_GATEWAY_VLAN70 }}
       TF_VAR_gateway_vlan40: ${{ vars.TF_GATEWAY_VLAN40 }}
       TF_VAR_gateway_vlan50: ${{ vars.TF_GATEWAY_VLAN50 }}
@@ -177,15 +176,6 @@ jobs:
           fi
 
           terraform -chdir=terraform/composants/01_core_infra $TF_ACTION $ARGS
-
-      # - name: "[CLEAN] Proxmox Bastion (si fail)"
-      #   if: failure() && steps.tf_bastion.outcome == 'failure'
-      #   run: |
-      #     for VMID in 401 402; do
-      #       ssh -o StrictHostKeyChecking=no root@${{ vars.TF_NAME_NODE_UNIX_1 }} "qm unlock $VMID || true"
-      #       ssh -o StrictHostKeyChecking=no root@${{ vars.TF_NAME_NODE_UNIX_2 }} "qm unlock $VMID || true"
-      #       ssh -o StrictHostKeyChecking=no root@${{ vars.TF_NAME_NODE_UNIX_3 }} "qm unlock $VMID || true"
-      #     done
       
       - name: "[HEALTHCHECK] Bastion"
         id: healthcheck_bastion
@@ -242,14 +232,6 @@ jobs:
           terraform -chdir=terraform/composants/01_core_infra ${{ github.event.inputs.terraform_action }} -auto-approve -parallelism=1 \
             -target='module.dhcp_1' \
             -target='module.dhcp_2'
-
-      # - name: "[CLEAN] Proxmox DHCP (si fail)"
-      #   if: failure() && steps.tf_dhcp.outcome == 'failure'
-      #   run: |
-      #     for VMID in 701 702; do
-      #       ssh -o StrictHostKeyChecking=no root@${{ vars.TF_IP_NODE_1 }} "qm unlock $VMID || true"
-      #       ssh -o StrictHostKeyChecking=no root@${{ vars.TF_IP_NODE_2 }} "qm unlock $VMID || true"
-      #     done
 
       - name: "[HEALTHCHECK] DHCP"
         id: healthcheck_dhcp
@@ -309,14 +291,6 @@ jobs:
             -target='module.dns_1' \
             -target='module.dns_2'
 
-      # - name: "[CLEAN] Proxmox DHCP (si fail)"
-      #   if: failure() && steps.tf_dhcp.outcome == 'failure'
-      #   run: |
-      #     for VMID in 701 702; do
-      #       ssh -o StrictHostKeyChecking=no root@${{ vars.TF_IP_NODE_1 }} "qm unlock $VMID || true"
-      #       ssh -o StrictHostKeyChecking=no root@${{ vars.TF_IP_NODE_2 }} "qm unlock $VMID || true"
-      #     done
-
       - name: "[HEALTHCHECK] DNS"
         id: healthcheck_dns
         if: |
@@ -373,14 +347,6 @@ jobs:
           terraform -chdir=terraform/composants/01_core_infra init
           terraform -chdir=terraform/composants/01_core_infra ${{ github.event.inputs.terraform_action }} -auto-approve -parallelism=1 \
             -target='module.ntp_1'
-
-      # - name: "[CLEAN] Proxmox NTP (si fail)"
-      #   if: failure() && steps.tf_ntp.outcome == 'failure'
-      #   run: |
-      #     for VMID in 701 702; do
-      #       ssh -o StrictHostKeyChecking=no root@${{ vars.TF_IP_NODE_1 }} "qm unlock $VMID || true"
-      #       ssh -o StrictHostKeyChecking=no root@${{ vars.TF_IP_NODE_2 }} "qm unlock $VMID || true"
-      #     done
 
       - name: "[HEALTHCHECK] NTP"
         id: healthcheck_ntp
@@ -465,47 +431,47 @@ jobs:
             echo "$IP est prêt pour SSH"
           done
 
-      # ==========================================
-      # BLOC 04 : RSYSLOG
-      # ==========================================
-      - name: "[TF] RSYSLOG"
-        if: |
-          github.event.inputs.run_terraform == 'true' && github.event.inputs.target_scope_tf == 'Sélection' && github.event.inputs.deploy_tf_rsys == 'true' ||
-          github.event.inputs.run_terraform == 'true' && github.event.inputs.target_scope_tf == 'Tous'
-        id: tf_rsys
-        run: |
-          export TF_WORKSPACE="nuuk-medilab-${{ github.event.inputs.environment }}-02-core-infra"
-          terraform -chdir=terraform/composants/02_core_infra init
-          terraform -chdir=terraform/composants/02_core_infra ${{ github.event.inputs.terraform_action }} -auto-approve -target='module.rsys_node3' -parallelism=1
+      # # ==========================================
+      # # BLOC 04 : RSYSLOG
+      # # ==========================================
+      # - name: "[TF] RSYSLOG"
+      #   if: |
+      #     github.event.inputs.run_terraform == 'true' && github.event.inputs.target_scope_tf == 'Sélection' && github.event.inputs.deploy_tf_rsys == 'true' ||
+      #     github.event.inputs.run_terraform == 'true' && github.event.inputs.target_scope_tf == 'Tous'
+      #   id: tf_rsys
+      #   run: |
+      #     export TF_WORKSPACE="nuuk-medilab-${{ github.event.inputs.environment }}-02-core-infra"
+      #     terraform -chdir=terraform/composants/02_core_infra init
+      #     terraform -chdir=terraform/composants/02_core_infra ${{ github.event.inputs.terraform_action }} -auto-approve -target='module.rsys_node3' -parallelism=1
 
-      - name: "[CLEAN] Proxmox RSYSLOG (si fail)"
-        if: failure() && steps.tf_rsys.outcome == 'failure'
-        run: |
-          for VMID in 501; do
-            ssh -o StrictHostKeyChecking=no root@${{ vars.TF_IP_NODE_3 }} "qm unlock $VMID || true"
-          done
+      # - name: "[CLEAN] Proxmox RSYSLOG (si fail)"
+      #   if: failure() && steps.tf_rsys.outcome == 'failure'
+      #   run: |
+      #     for VMID in 501; do
+      #       ssh -o StrictHostKeyChecking=no root@${{ vars.TF_IP_NODE_3 }} "qm unlock $VMID || true"
+      #     done
 
-      - name: "[HEALTHCHECK] RSYSLOG"
-        id: healthcheck_rsys
-        if: |
-          success() && github.event.inputs.run_ansible == 'true' && (
-            github.event.inputs.target_scope_ans == 'Tous' ||
-            (github.event.inputs.target_scope_ans == 'Sélection' && github.event.inputs.deploy_ans_rsys == 'true')
-          )
-        run: |
-          IP1="${{ vars.TF_IP_RSYS_01 }}"
+      # - name: "[HEALTHCHECK] RSYSLOG"
+      #   id: healthcheck_rsys
+      #   if: |
+      #     success() && github.event.inputs.run_ansible == 'true' && (
+      #       github.event.inputs.target_scope_ans == 'Tous' ||
+      #       (github.event.inputs.target_scope_ans == 'Sélection' && github.event.inputs.deploy_ans_rsys == 'true')
+      #     )
+      #   run: |
+      #     IP1="${{ vars.TF_IP_RSYS_01 }}"
 
-          echo "Attente du réseau sur $IP1..."
-          for IP in $IP1; do
-            timeout 180s bash -c "until ping -c 1 -W 1 $IP > /dev/null; do echo 'Waiting for $IP...'; sleep 5; done"
-            timeout 120s bash -c "until nc -zvw1 $IP 22; do sleep 5; done"
-            echo "$IP est prêt pour SSH"
-          done
+      #     echo "Attente du réseau sur $IP1..."
+      #     for IP in $IP1; do
+      #       timeout 180s bash -c "until ping -c 1 -W 1 $IP > /dev/null; do echo 'Waiting for $IP...'; sleep 5; done"
+      #       timeout 120s bash -c "until nc -zvw1 $IP 22; do sleep 5; done"
+      #       echo "$IP est prêt pour SSH"
+      #     done
 
-      - name: "[ANS] Config RSYSLOG"
-        if: |
-          success() &&
-          steps.healthcheck_rsys.outcome == 'success'
-        run: |
-          cd ansible
-          ansible-playbook -i inventory/inventory.proxmox.yml 03_deploy_syslog.yml
+      # - name: "[ANS] Config RSYSLOG"
+      #   if: |
+      #     success() &&
+      #     steps.healthcheck_rsys.outcome == 'success'
+      #   run: |
+      #     cd ansible
+      #     ansible-playbook -i inventory/inventory.proxmox.yml 03_deploy_syslog.yml
