feat(cicd):add grafana tf

diff --git a/.github/workflows/02-admin-zone.yml b/.github/workflows/02-admin-zone.yml
--- a/.github/workflows/02-admin-zone.yml
+++ b/.github/workflows/02-admin-zone.yml
@@ -121,6 +121,10 @@ jobs:
 
       TF_VAR_ip_haproxy_1: ${{ vars.TF_IP_HAPROXY_1 }}
       TF_VAR_ip_haproxy_2: ${{ vars.TF_IP_HAPROXY_2 }}
+      TF_VAR_ipv4_cidr_vlan120: ${{ vars.TF_IPV4_CIDR_VLAN120 }}
+      TF_VAR_gateway_vlan50: ${{ vars.TF_GATEWAY_VLAN50 }}
+      TF_VAR_ipv4_cidr_vlan50: ${{ vars.TF_IPV4_CIDR_VLAN50 }}
+      TF_VAR_ip_grafana: ${{ vars.TF_IP_GRAFANA }}
       TF_VAR_gateway_vlan120: ${{ vars.TF_GATEWAY_VLAN120 }}
       TF_VAR_ip_node_1: ${{ vars.TF_IP_NODE_1 }}
       TF_VAR_ip_node_2: ${{ vars.TF_IP_NODE_2 }}
@@ -231,3 +235,75 @@ jobs:
       #   run: |
       #     cd ansible
       #     ansible-playbook -i inventory/inventory.proxmox.yml 10_deploy_haadmin.yml
+
+      # ==========================================
+      # BLOC 02 : GRAFANA
+      # ==========================================
+      - name: "[TF] GRAFANA"
+        if: |
+          github.event.inputs.run_terraform == 'true' && github.event.inputs.target_scope_tf == 'Sélection' && github.event.inputs.deploy_tf_grafana == 'true' ||
+          github.event.inputs.run_terraform == 'true' && github.event.inputs.target_scope_tf == 'Tous'
+        id: tf_grafana
+        continue-on-error: false
+        run: |
+          export TF_WORKSPACE="nuuk-medilab-${{ github.event.inputs.environment }}-02-core-infra"
+          terraform -chdir=terraform/composants/02_admin_zone init -upgrade
+
+          TF_ACTION="${{ github.event.inputs.terraform_action }}"
+          ARGS="-target=module.grafana -parallelism=1"
+
+          if [ "$TF_ACTION" != "plan" ]; then
+            ARGS="$ARGS -auto-approve"
+          fi
+
+          terraform -chdir=terraform/composants/02_admin_zone $TF_ACTION $ARGS
+
+      # - name: "[CLEAN] Proxmox GRAFANA (si fail)"
+      #   if: failure() && steps.tf_grafana.outcome == 'failure'
+      #   run: |
+      #     for VMID in 401 402; do
+      #       ssh -o StrictHostKeyChecking=no root@${{ vars.TF_NAME_NODE_UNIX_1 }} "qm unlock $VMID || true"
+      #       ssh -o StrictHostKeyChecking=no root@${{ vars.TF_NAME_NODE_UNIX_2 }} "qm unlock $VMID || true"
+      #       ssh -o StrictHostKeyChecking=no root@${{ vars.TF_NAME_NODE_UNIX_3 }} "qm unlock $VMID || true"
+      #     done
+      
+      - name: "[HEALTHCHECK] GRAFANA"
+        id: healthcheck_grafana
+        if: |
+          success() &&
+          github.event.inputs.run_ansible == 'true' && (
+            github.event.inputs.target_scope_ans == 'Tous' ||
+            (github.event.inputs.target_scope_ans == 'Sélection' && github.event.inputs.deploy_ans_grafana == 'true')
+          )
+        run: |
+          IP1="${{ vars.TF_IP_GRAFANA }}"
+
+          echo "Attente du réseau sur $IP1..."
+          for IP in $IP1; do
+            timeout 180s bash -c "until ping -c 1 -W 1 $IP > /dev/null; do echo 'Waiting for $IP...'; sleep 5; done"
+            timeout 120s bash -c "until nc -zvw1 $IP 22; do sleep 5; done"
+            echo "$IP est prêt pour SSH"
+          done
+
+      - name: "[SSH] Trust GRAFANA host keys"
+        if: |
+          success() &&
+          steps.healthcheck_grafana.outcome == 'success'
+        run: |
+          mkdir -p ~/.ssh
+          chmod 700 ~/.ssh
+      
+          for IP in "${{ vars.TF_IP_GRAFANA }}"; do
+            ssh-keygen -R "$IP" || true
+            ssh-keyscan -H "$IP" >> ~/.ssh/known_hosts
+          done
+
+          chmod 600 ~/.ssh/known_hosts
+
+      # - name: "[ANS] Config GRAFANA"
+      #   if: |
+      #     success() &&
+      #     steps.healthcheck_grafana.outcome == 'success'
+      #   run: |
+      #     cd ansible
+      #     ansible-playbook -i inventory/inventory.proxmox.yml 11_deploy_grafana.yml
